export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_SUCCESS = "BOOKS_SUCCESS";
export const BOOKS_FAIL = "BOOKS_FAIL";
export const CHARACTER_REQUEST = "CHARACTER_REQUEST";
export const CHARACTER_SUCCESS = "CHARACTER_SUCCESS";
export const CHARACTER_FAIL = "CHARACTER_FAIL";
